WIP - Config File and StorageProxy Abstractions
USCDataScience/sparkler pull request #216
Opened 2021-03-03 17:26 UTC by Kefaun2601

## What changes were proposed in this pull request?

Changes to sparkler-default.yaml configuration:
- Abstracted out crawldb.uri into crawldb.backend, solr.uri, and elasticsearch.uri

Added StorageProxy and StorageProxyFactory:
- WIP Abstracting out Solr implementation into the SolrProxy wrapper
- StorageProxyFactory for returning the correct StorageProxy (SolrProxy or ElasticsearchProxy) based on the yaml config file

**Is this related to an already existing issue on sparkler?**  
Related to #211 

**Will it close an existing issue?**  
Does not close an issue yet.

### How was this patch tested?

This patch was tested by running "mvn clean package" within the "sparkler-core" directory. The tests currently pass, and it builds successfully.

2021-03-03 17:47 UTC, lewismc requested changes
This looks REALLY good so far. I've made some trivial comments to get you in the right direction. Thank you for working on this guys and posting your pull requests early for review. It makes a huge difference.
Please continue to update this PR and I will review incrementally.

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/CrawlDbRDD.scala
> +    val solr = proxy.getClient()
Change variable name from `solr` to `client`

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/MemexCrawlDbRDD.scala
> +    val solr = proxy.getClient()
Change variable name from `solr` to `client`

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/MemexDeepCrawlRDD.scala
> +    val solr = proxy.getClient()
Change variable name from `solr` to `client`

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/pipeline/Crawler.scala
> +  var sparkSolr: String = sparklerConf.getDatabaseURI()
Change variable name from `sparkSolr` to `sparkStorage`

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/pipeline/Crawler.scala
> +    val solrc = this.job.newStorageProxy()
Change variable name from `solrc` to `sProxy` or `storageProxy`

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/service/Injector.scala
> +  var sparkSolr: String = conf.getDatabaseURI()
Change variable name from `sparkSolr` to `sparkStorage`

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/service/Injector.scala
> +    val dbClient = job.newStorageProxy()
Change variable name from `dbClient` to `sProxy` or `storageProxy`

2021-03-03 17:47 UTC, lewismc commented on sparkler-core/sparkler-app/src/main/scala/edu/usc/irds/sparkler/storage/StorageProxy.scala
> +  * @since 3/2/2021
This should not be a date it should be a version release. You can find this in `pom.xml`

2021-03-06 18:40 UTC, lewismc commented
This is looking better @kyan2601 thanks.

2021-03-13 01:34 UTC, Kefaun2601 commented
Confirmed that I can run a crawl job and view the data on the Banana dashboard. Did not notice any regressions in functionality that may have arose from the implemented Solr abstractions.

Commands run (as per the [repo README](https://github.com/USCDataScience/sparkler/blob/master/README.md)):
<pre>
# Start in the sparkler-core directory
cd sparkler-core

# Run script to start docker container and forward ports to host
bash ./bin/dockler.sh

# Inject seed urls
/data/sparkler/bin/sparkler.sh inject -id 1 -su 'http://www.bbc.com/news'

# Start the crawl job
/data/sparkler/bin/sparkler.sh crawl -id 1 -tn 100 -i 2
</pre>

Access the Banana dashboard at [http://localhost:8983/banana/](http://localhost:8983/banana/) to see the data.

2021-03-13 02:14 UTC, lewismc commented
HJi @Kefaun2601 this PR and branch has a conflict which must be resolved. Once that's done, please tag me and I will test it out. Thank you

2021-03-13 02:42 UTC, Kefaun2601 commented
@lewismc Resolved the merge conflicts. Could you please review it? Thanks!

2021-03-13 02:44 UTC, Kefaun2601 commented
Added documentation for specifying the storage engine to use in the config file (sparkler-default.yaml):
[https://github.com/USCDataScience/sparkler/wiki/Specifying-CrawlDB-in-Config](https://github.com/USCDataScience/sparkler/wiki/Specifying-CrawlDB-in-Config)

Documentation on the StorageProxyFactory abstraction will be coming.

2021-03-13 18:28 UTC, Kefaun2601 commented
Added documentation for the StorageProxyFactory abstraction. Will build on this documentation as we expand the factory.

[https://github.com/USCDataScience/sparkler/wiki/StorageProxyFactory-Abstraction](https://github.com/USCDataScience/sparkler/wiki/StorageProxyFactory-Abstraction)

2021-03-21 18:09 UTC, merged

2021-03-21 18:09 UTC, lewismc commented
Also confirmed that this DOES NOT introduce a regression. Thank you @felixloesing and @kyan2601